spring:
  application:
    name: config
  profiles:
    active: native
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/GiorgiSheklashvili/smart-order-config.git"
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true
        native:
          search-locations: file:///D:/smart-order/config/local-config
    bus:
      enabled: true
      id: ${spring.application.name}:${spring.profiles.active}:${random.uuid}
  kafka:
    bootstrap-servers: 'localhost:9092'
management:
  endpoints:
    web:
      exposure:
        include: 'busrefresh,monitor'
server:
  port: 8071