version: '3.8'

services:
  kafka:
      image: bitnami/kafka:latest
      container_name: kafka_smart_order
      ports:
        - "9092:9092"
      environment:
        - KAFKA_CFG_NODE_ID=1
        - KAFKA_CFG_PROCESS_ROLES=broker,controller
        - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
        - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,INTERNAL://:9094
        - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092,INTERNAL://kafka:9094
        - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT
        - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INTERNAL
        - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
        - KAFKA_CFG_LOG_RETENTION_HOURS=1
        - KAFKA_CFG_LOG_RETENTION_BYTES=104857600  # 100MB max
        - ALLOW_PLAINTEXT_LISTENER=yes
      volumes:
        - ./kafka:/bitnami/kafka

  kafdrop:
      image: obsidiandynamics/kafdrop:latest
      container_name: kafdrop
      depends_on:
        - kafka
      ports:
        - "9000:9000"
      environment:
        - KAFKA_BROKERCONNECT=kafka:9094
